/**
 * AUTO-GENERATED by scripts/generate-category-media.mjs — do not edit by
 * hand. Regenerated automatically before `npm run dev`/`npm run build`,
 * or manually via `npm run generate:media`, from whatever files sit in
 * public/work/<category-slug>/.
 */
import type { Slide } from "@/app/components/marketing/WorkSlider";

export const generatedCategoryMedia: Record<string, Slide[]> = {
  "3d-animation": [
    {
      "name": "3d Animation 01",
      "img": "/work/3d-animation/3d-animation-01.mp4"
    },
    {
      "name": "3d Animation 02",
      "img": "/work/3d-animation/3d-animation-02.mp4"
    },
    {
      "name": "3d Animation 03",
      "img": "/work/3d-animation/3d-animation-03.mp4"
    },
    {
      "name": "3d Animation 04",
      "img": "/work/3d-animation/3d-animation-04.mp4"
    },
    {
      "name": "3d Animation 05",
      "img": "/work/3d-animation/3d-animation-05.mp4"
    }
  ],
  "background-animations": [
    {
      "name": "Background Animations 01",
      "img": "/work/background-animations/background-animations-01.webm"
    },
    {
      "name": "Background Animations 02",
      "img": "/work/background-animations/background-animations-02.webm"
    },
    {
      "name": "Background Animations 03",
      "img": "/work/background-animations/background-animations-03.webm"
    },
    {
      "name": "Background Animations 04",
      "img": "/work/background-animations/background-animations-04.webm"
    },
    {
      "name": "Background Animations 05",
      "img": "/work/background-animations/background-animations-05.webm"
    },
    {
      "name": "Background Animations 06",
      "img": "/work/background-animations/background-animations-06.webm"
    }
  ],
  "grid-animations": [
    {
      "name": "Grid Animations 01",
      "img": "/work/grid-animations/grid-animations-01.mp4"
    },
    {
      "name": "Grid Animations 02",
      "img": "/work/grid-animations/grid-animations-02.webm"
    },
    {
      "name": "Grid Animations 03",
      "img": "/work/grid-animations/grid-animations-03.webm"
    },
    {
      "name": "Grid Animations 04",
      "img": "/work/grid-animations/grid-animations-04.webm"
    },
    {
      "name": "Grid Animations 05",
      "img": "/work/grid-animations/grid-animations-05.webm"
    },
    {
      "name": "Grid Animations 06",
      "img": "/work/grid-animations/grid-animations-06.webm"
    }
  ],
  "hero-animations": [
    {
      "name": "Hero Animations 01",
      "img": "/work/hero-animations/hero-animations-01.mp4"
    },
    {
      "name": "Hero Animations 02",
      "img": "/work/hero-animations/hero-animations-02.mp4"
    },
    {
      "name": "Hero Animations 03",
      "img": "/work/hero-animations/hero-animations-03.mp4"
    },
    {
      "name": "Hero Animations 04",
      "img": "/work/hero-animations/hero-animations-04.mp4"
    },
    {
      "name": "Hero Animations 05",
      "img": "/work/hero-animations/hero-animations-05.mp4"
    }
  ],
  "hover-effects": [
    {
      "name": "Hover Effects 01",
      "img": "/work/hover-effects/hover-effects-01.mp4"
    },
    {
      "name": "Hover Effects 02",
      "img": "/work/hover-effects/hover-effects-02.mp4"
    },
    {
      "name": "Hover Effects 03",
      "img": "/work/hover-effects/hover-effects-03.mp4"
    },
    {
      "name": "Hover Effects 04",
      "img": "/work/hover-effects/hover-effects-04.mp4"
    },
    {
      "name": "Hover Effects 05",
      "img": "/work/hover-effects/hover-effects-05.mp4"
    }
  ],
  "mouse-effects": [
    {
      "name": "Mouse Effects 01",
      "img": "/work/mouse-effects/mouse-effects-01.mp4"
    },
    {
      "name": "Mouse Effects 02",
      "img": "/work/mouse-effects/mouse-effects-02.mp4"
    },
    {
      "name": "Mouse Effects 03",
      "img": "/work/mouse-effects/mouse-effects-03.mp4"
    },
    {
      "name": "Mouse Effects 04",
      "img": "/work/mouse-effects/mouse-effects-04.webm"
    },
    {
      "name": "Mouse Effects 05",
      "img": "/work/mouse-effects/mouse-effects-05.webm"
    },
    {
      "name": "Mouse Effects 06",
      "img": "/work/mouse-effects/mouse-effects-06.webm"
    },
    {
      "name": "Mouse Effects 07",
      "img": "/work/mouse-effects/mouse-effects-07.webm"
    }
  ],
  "navigation-menus": [
    {
      "name": "Navigation Menus 01",
      "img": "/work/navigation-menus/navigation-menus-01.mp4"
    },
    {
      "name": "Navigation Menus 02",
      "img": "/work/navigation-menus/navigation-menus-02.mp4"
    },
    {
      "name": "Navigation Menus 03",
      "img": "/work/navigation-menus/navigation-menus-03.mp4"
    },
    {
      "name": "Navigation Menus 04",
      "img": "/work/navigation-menus/navigation-menus-04.webm"
    },
    {
      "name": "Navigation Menus 05",
      "img": "/work/navigation-menus/navigation-menus-05.mp4"
    }
  ],
  "page-transitions": [
    {
      "name": "Page Transitions 01",
      "img": "/work/page-transitions/page-transitions-01.mp4"
    },
    {
      "name": "Page Transitions 02",
      "img": "/work/page-transitions/page-transitions-02.mp4"
    },
    {
      "name": "Page Transitions 03",
      "img": "/work/page-transitions/page-transitions-03.mp4"
    },
    {
      "name": "Page Transitions 04",
      "img": "/work/page-transitions/page-transitions-04.mp4"
    },
    {
      "name": "Page Transitions 05",
      "img": "/work/page-transitions/page-transitions-05.mp4"
    }
  ],
  "physics-effects": [
    {
      "name": "Physics Effects 01",
      "img": "/work/physics-effects/physics-effects-01.mp4"
    },
    {
      "name": "Physics Effects 02",
      "img": "/work/physics-effects/physics-effects-02.mp4"
    },
    {
      "name": "Physics Effects 03",
      "img": "/work/physics-effects/physics-effects-03.mp4"
    },
    {
      "name": "Physics Effects 04",
      "img": "/work/physics-effects/physics-effects-04.mp4"
    },
    {
      "name": "Physics Effects 05",
      "img": "/work/physics-effects/physics-effects-05.mp4"
    }
  ],
  "scroll-animation": [
    {
      "name": "Scroll Animation 01",
      "img": "/work/scroll-animation/scroll-animation-01.mp4"
    },
    {
      "name": "Scroll Animation 02",
      "img": "/work/scroll-animation/scroll-animation-02.mp4"
    },
    {
      "name": "Scroll Animation 03",
      "img": "/work/scroll-animation/scroll-animation-03.mp4"
    },
    {
      "name": "Scroll Animation 04",
      "img": "/work/scroll-animation/scroll-animation-04.mp4"
    }
  ],
  "svg-animations": [
    {
      "name": "Svg Animations 01",
      "img": "/work/svg-animations/svg-animations-01.mp4"
    },
    {
      "name": "Svg Animations 02",
      "img": "/work/svg-animations/svg-animations-02.mp4"
    },
    {
      "name": "Svg Animations 03",
      "img": "/work/svg-animations/svg-animations-03.mp4"
    },
    {
      "name": "Svg Animations 04",
      "img": "/work/svg-animations/svg-animations-04.mp4"
    },
    {
      "name": "Svg Animations 05",
      "img": "/work/svg-animations/svg-animations-05.mp4"
    }
  ],
  "text-animations": [
    {
      "name": "Text Animations 01",
      "img": "/work/text-animations/text-animations-01.mp4"
    },
    {
      "name": "Text Animations 02",
      "img": "/work/text-animations/text-animations-02.mp4"
    },
    {
      "name": "Text Animations 03",
      "img": "/work/text-animations/text-animations-03.mp4"
    },
    {
      "name": "Text Animations 04",
      "img": "/work/text-animations/text-animations-04.mp4"
    },
    {
      "name": "Text Animations 05",
      "img": "/work/text-animations/text-animations-05.mp4"
    }
  ],
  "webgl-threejs-effects": [
    {
      "name": "Webgl Threejs Effects 01",
      "img": "/work/webgl-threejs-effects/webgl-threejs-effects-01.mp4"
    },
    {
      "name": "Webgl Threejs Effects 02",
      "img": "/work/webgl-threejs-effects/webgl-threejs-effects-02.webm"
    },
    {
      "name": "Webgl Threejs Effects 03",
      "img": "/work/webgl-threejs-effects/webgl-threejs-effects-03.webm"
    },
    {
      "name": "Webgl Threejs Effects 04",
      "img": "/work/webgl-threejs-effects/webgl-threejs-effects-04.webm"
    },
    {
      "name": "Webgl Threejs Effects 05",
      "img": "/work/webgl-threejs-effects/webgl-threejs-effects-05.webm"
    },
    {
      "name": "Webgl Threejs Effects 06",
      "img": "/work/webgl-threejs-effects/webgl-threejs-effects-06.webm"
    }
  ]
};
